# Generated by Django 5.0.2 on 2024-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0012_delete_id_card_remove_service_man_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_man',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='service_man',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
