# Generated by Django 5.0.2 on 2024-02-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0016_alter_customer_latitude_alter_customer_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11),
        ),
    ]
