# Generated by Django 4.2.7 on 2024-03-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0017_alter_customer_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_man',
            name='city',
        ),
    ]
