# Generated by Django 4.2.7 on 2024-03-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0018_remove_service_man_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_man',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_service.city'),
        ),
    ]
